apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv2
  labels:
    app: example2
    context: virtualizacao
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/data2