apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  labels:
    app: example
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    name: example-pv-claim
    namespace: default
  hostPath:
    path: /mnt/data