apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pv-2-claim
  namespace: default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: example2
      context: virtualizacao