apiVersion: v1
kind: Pod
metadata:
  name: random-number-3
  labels:
    name: random-number-3
spec:
  containers:
  - name: random-number
    image: alpine
    command: ["/bin/sh", "-c"]
    args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
    volumeMounts:
      - mountPath: /opt
        name: data-volume
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: example-pv-2-claim
